version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: github_repo_postgres
    restart: always
    environment:
      POSTGRES_DB: github_repo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5300:5432"
    volumes:
      - github_repo_data:/var/lib/postgresql/data

volumes:
  github_repo_data:
